# Generated by Django 5.0 on 2024-01-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_servies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
